interface IconProps {
  name: string;
  size?: number;
  className?: string;
  filled?: boolean;
}

const iconAliases: Record<string, string> = {
  pizza: "local_pizza",
  burger: "lunch_dining",
  coffee: "coffee",
  drink: "local_bar",
  dessert: "cake",
  salad: "salad",
  soup: "soup_kitchen",
  sushi: "set_meal",
  food: "restaurant",
  menu: "menu_book",
  category: "category",
  all: "grid_view",
  home: "home",
  orders: "receipt_long",
  profile: "person",
  cart: "shopping_cart",
  delivery: "moped",
  takeaway: "shopping_bag",
  location: "location_on",
  phone: "phone",
  star: "star",
  map: "map",
  search: "search",
  back: "arrow_back_ios",
  close: "close",
  add: "add",
  remove: "remove",
  check: "check_circle",
  success: "check_circle",
  error: "error",
  warning: "warning",
  info: "info",
  card: "credit_card",
  cash: "payments",
  plus: "add",
  minus: "remove",
  clock: "schedule",
  "chevron-right": "chevron_right",
  "chevron-left": "chevron_left",
  "chevron-down": "expand_more",
  "chevron-up": "expand_less",
  arrow_forward: "arrow_forward_ios",
  bag: "shopping_bag",
  notification: "notifications",
  bell: "notifications",
  edit: "edit",
  trash: "delete",
  delete: "delete",
  user: "person",
  logout: "logout",
  login: "login",
  history: "history",
  receipt: "receipt_long",
  wallet: "account_balance_wallet",
  copy: "content_copy",
  share: "share",
  filter: "filter_list",
  sort: "sort",
  settings: "settings",
  help: "help",
  language: "language",
  globe: "language",
  heart: "favorite",
  favorite: "favorite",
  refresh: "refresh",
  download: "download",
  upload: "upload",
  send: "send",
  mail: "mail",
  email: "mail",
  message: "chat",
  chat: "chat",
  call: "call",
  visibility: "visibility",
  eye: "visibility",
  eye_off: "visibility_off",
  lock: "lock",
  unlock: "lock_open",
  sparkles: "auto_awesome",
  spark: "auto_awesome",
  recommend: "auto_awesome",
  calendar: "calendar_today",
  event: "event",
  qr: "qr_code_2",
  qr_code: "qr_code_2",
  restaurant: "restaurant",
  scan: "qr_code_scanner",
  tune: "tune",
  replay: "replay",
  near_me: "near_me",
  bolt: "bolt",
  delivery_dining: "delivery_dining",
  trending: "trending_up",
  rating: "auto_awesome",
  payments: "payments",
  receipt_long: "receipt_long",
};

export function Icon({ name, size = 24, className = "", filled = false }: IconProps) {
  const normalized = iconAliases[name?.toLowerCase()] || name || "category";
  return (
    <span
      className={`material-symbols-${filled ? "rounded" : "outlined"} ${className}`}
      style={{ fontSize: size, lineHeight: 1, userSelect: "none" }}
    >
      {normalized}
    </span>
  );
}
