// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QrMenu.Infrastructure.Data;

#nullable disable

namespace QrMenu.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224095757_AddPaymentLink")]
    partial class AddPaymentLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QrMenu.Core.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@qrmenu.com",
                            Name = "Администратор",
                            PasswordHash = "$2a$11$MNdhehrSFFENRCQ079MwY.iY.mQTrMLWum0fap.IbW2ndl2qceyCK"
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("AvailableFrom")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("AvailableTo")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTemporarilyDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 2, 24, 9, 57, 57, 18, DateTimeKind.Utc).AddTicks(1402),
                            Icon = "local_pizza",
                            IsActive = true,
                            IsTemporarilyDisabled = false,
                            Name = "Пицца",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 2, 24, 9, 57, 57, 18, DateTimeKind.Utc).AddTicks(1454),
                            Icon = "lunch_dining",
                            IsActive = true,
                            IsTemporarilyDisabled = false,
                            Name = "Бургеры",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 2, 24, 9, 57, 57, 18, DateTimeKind.Utc).AddTicks(1460),
                            Icon = "local_cafe",
                            IsActive = true,
                            IsTemporarilyDisabled = false,
                            Name = "Напитки",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2026, 2, 24, 9, 57, 57, 18, DateTimeKind.Utc).AddTicks(1464),
                            Icon = "cake",
                            IsActive = true,
                            IsTemporarilyDisabled = false,
                            Name = "Десерты",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2026, 2, 24, 9, 57, 57, 18, DateTimeKind.Utc).AddTicks(1469),
                            Icon = "eco",
                            IsActive = true,
                            IsTemporarilyDisabled = false,
                            Name = "Салаты",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Полное меню нашего ресторана",
                            IsActive = true,
                            Name = "Основное меню",
                            RestaurantId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MenuId", "CategoryId")
                        .IsUnique();

                    b.ToTable("MenuCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            MenuId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            MenuId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            MenuId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            MenuId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            MenuId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentLink")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uuid");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tax")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = false,
                            PaymentMethod = "cash",
                            SpecialInstructions = "Без лука",
                            Status = 2,
                            Subtotal = 970m,
                            TableId = new Guid("55555555-5555-5555-5555-555555555555"),
                            TableNumber = 0,
                            Tax = 97m,
                            Total = 1067m,
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("22222222-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 1, 2, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = false,
                            PaymentMethod = "cash",
                            Status = 1,
                            Subtotal = 520m,
                            TableId = new Guid("55555555-5555-5555-5555-555555555555"),
                            TableNumber = 0,
                            Tax = 52m,
                            Total = 572m,
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedAddons")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SizeName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 24, 9, 57, 57, 18, DateTimeKind.Utc).AddTicks(3056),
                            OrderId = new Guid("11111111-5555-5555-5555-555555555555"),
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProductName = "Маргарита",
                            Quantity = 1,
                            SelectedAddons = "Дополнительный сыр",
                            SizeName = "Средняя (30 см)",
                            Status = 1,
                            TotalPrice = 550m,
                            UnitPrice = 550m
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 24, 9, 57, 57, 18, DateTimeKind.Utc).AddTicks(3067),
                            OrderId = new Guid("11111111-5555-5555-5555-555555555555"),
                            ProductId = new Guid("11111111-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ProductName = "Классический бургер",
                            Quantity = 1,
                            SelectedAddons = "",
                            Status = 1,
                            TotalPrice = 350m,
                            UnitPrice = 350m
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 24, 9, 57, 57, 18, DateTimeKind.Utc).AddTicks(3075),
                            OrderId = new Guid("11111111-5555-5555-5555-555555555555"),
                            ProductId = new Guid("11111111-cccc-cccc-cccc-cccccccccccc"),
                            ProductName = "Кола",
                            Quantity = 1,
                            SelectedAddons = "",
                            SizeName = "0.5л",
                            Status = 1,
                            TotalPrice = 110m,
                            UnitPrice = 110m
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 24, 9, 57, 57, 18, DateTimeKind.Utc).AddTicks(3082),
                            OrderId = new Guid("22222222-5555-5555-5555-555555555555"),
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProductName = "Пепперони",
                            Quantity = 1,
                            SelectedAddons = "",
                            SizeName = "Маленькая (25 см)",
                            Status = 1,
                            TotalPrice = 520m,
                            UnitPrice = 520m
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Phone", "Code");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MenuId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BasePrice = 450m,
                            Calories = 850,
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Классическая пицца с томатным соусом, моцареллой и базиликом",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Маргарита",
                            PrepTimeMinutes = 20,
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BasePrice = 520m,
                            Calories = 950,
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Пицца с острой колбасой пепперони и сыром моцарелла",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Пепперони",
                            PrepTimeMinutes = 20,
                            Rating = 4.9m
                        },
                        new
                        {
                            Id = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BasePrice = 480m,
                            Calories = 880,
                            CategoryId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Пицца с ветчиной, ананасами и сыром",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Гавайская",
                            PrepTimeMinutes = 20,
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = new Guid("11111111-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BasePrice = 350m,
                            Calories = 650,
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Сочная говяжья котлета с салатом, томатами и соусом",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Классический бургер",
                            PrepTimeMinutes = 15,
                            Rating = 4.7m
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BasePrice = 390m,
                            Calories = 750,
                            CategoryId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Бургер с двойным сыром чеддер и фирменным соусом",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Чизбургер",
                            PrepTimeMinutes = 15,
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = new Guid("11111111-cccc-cccc-cccc-cccccccccccc"),
                            BasePrice = 80m,
                            Calories = 140,
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Освежающий газированный напиток",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Кола",
                            PrepTimeMinutes = 2,
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = new Guid("22222222-cccc-cccc-cccc-cccccccccccc"),
                            BasePrice = 120m,
                            Calories = 110,
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Свежевыжатый апельсиновый сок",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Апельсиновый сок",
                            PrepTimeMinutes = 5,
                            Rating = 4.9m
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-cccccccccccc"),
                            BasePrice = 150m,
                            Calories = 120,
                            CategoryId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ароматный кофе с молочной пенкой",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Капучино",
                            PrepTimeMinutes = 5,
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = new Guid("11111111-dddd-dddd-dddd-dddddddddddd"),
                            BasePrice = 280m,
                            Calories = 450,
                            CategoryId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Классический итальянский десерт с кофейным вкусом",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Тирамису",
                            PrepTimeMinutes = 5,
                            Rating = 4.9m
                        },
                        new
                        {
                            Id = new Guid("22222222-dddd-dddd-dddd-dddddddddddd"),
                            BasePrice = 250m,
                            Calories = 380,
                            CategoryId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Нежный чизкейк с ягодным соусом",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Чизкейк",
                            PrepTimeMinutes = 5,
                            Rating = 4.7m
                        },
                        new
                        {
                            Id = new Guid("11111111-eeee-eeee-eeee-eeeeeeeeeeee"),
                            BasePrice = 320m,
                            Calories = 350,
                            CategoryId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Салат с куриной грудкой, сухариками и соусом цезарь",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Цезарь с курицей",
                            PrepTimeMinutes = 10,
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = new Guid("22222222-eeee-eeee-eeee-eeeeeeeeeeee"),
                            BasePrice = 280m,
                            Calories = 280,
                            CategoryId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Свежие овощи с сыром фета и оливками",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Греческий",
                            PrepTimeMinutes = 10,
                            Rating = 4.6m
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.ProductAddon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAddons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-aaaa-aaaaaaaaaaaa"),
                            IsAvailable = true,
                            Name = "Дополнительный сыр",
                            Price = 50m,
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-1111-aaaa-aaaaaaaaaaaa"),
                            IsAvailable = true,
                            Name = "Грибы",
                            Price = 40m,
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-1111-aaaa-aaaaaaaaaaaa"),
                            IsAvailable = true,
                            Name = "Оливки",
                            Price = 35m,
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-1111-aaaa-aaaaaaaaaaaa"),
                            IsAvailable = true,
                            Name = "Дополнительный сыр",
                            Price = 50m,
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-1111-aaaa-aaaaaaaaaaaa"),
                            IsAvailable = true,
                            Name = "Халапеньо",
                            Price = 30m,
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-bbbb-bbbbbbbbbbbb"),
                            IsAvailable = true,
                            Name = "Бекон",
                            Price = 60m,
                            ProductId = new Guid("11111111-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-1111-bbbb-bbbbbbbbbbbb"),
                            IsAvailable = true,
                            Name = "Яйцо",
                            Price = 40m,
                            ProductId = new Guid("11111111-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-1111-bbbb-bbbbbbbbbbbb"),
                            IsAvailable = true,
                            Name = "Дополнительная котлета",
                            Price = 120m,
                            ProductId = new Guid("11111111-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-1111-bbbb-bbbbbbbbbbbb"),
                            IsAvailable = true,
                            Name = "Бекон",
                            Price = 60m,
                            ProductId = new Guid("22222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-1111-bbbb-bbbbbbbbbbbb"),
                            IsAvailable = true,
                            Name = "Дополнительный сыр",
                            Price = 40m,
                            ProductId = new Guid("22222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.ProductSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PriceModifier")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDefault = true,
                            Name = "Маленькая (25 см)",
                            PriceModifier = 0m,
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDefault = false,
                            Name = "Средняя (30 см)",
                            PriceModifier = 100m,
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDefault = false,
                            Name = "Большая (35 см)",
                            PriceModifier = 200m,
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDefault = true,
                            Name = "Маленькая (25 см)",
                            PriceModifier = 0m,
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDefault = false,
                            Name = "Средняя (30 см)",
                            PriceModifier = 100m,
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("33333333-2222-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsDefault = false,
                            Name = "Большая (35 см)",
                            PriceModifier = 200m,
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-cccc-cccc-cccccccccccc"),
                            IsDefault = true,
                            Name = "0.33л",
                            PriceModifier = 0m,
                            ProductId = new Guid("11111111-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("22222222-1111-cccc-cccc-cccccccccccc"),
                            IsDefault = false,
                            Name = "0.5л",
                            PriceModifier = 30m,
                            ProductId = new Guid("11111111-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("33333333-1111-cccc-cccc-cccccccccccc"),
                            IsDefault = false,
                            Name = "1л",
                            PriceModifier = 60m,
                            ProductId = new Guid("11111111-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("11111111-3333-cccc-cccc-cccccccccccc"),
                            IsDefault = true,
                            Name = "Маленький",
                            PriceModifier = 0m,
                            ProductId = new Guid("33333333-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("22222222-3333-cccc-cccc-cccccccccccc"),
                            IsDefault = false,
                            Name = "Средний",
                            PriceModifier = 40m,
                            ProductId = new Guid("33333333-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-cccc-cccc-cccccccccccc"),
                            IsDefault = false,
                            Name = "Большой",
                            PriceModifier = 70m,
                            ProductId = new Guid("33333333-cccc-cccc-cccc-cccccccccccc")
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AcceptingOrders")
                        .HasColumnType("boolean");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AlifGate")
                        .HasColumnType("text");

                    b.Property<string>("AlifKey")
                        .HasColumnType("text");

                    b.Property<string>("AlifPassword")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DcArticul")
                        .HasColumnType("text");

                    b.Property<string>("DcMerchantId")
                        .HasColumnType("text");

                    b.Property<string>("DcSecretKey")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PauseMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PaymentLink")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AcceptingOrders = true,
                            Address = "ул. Примерная, 123",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Уютное кафе с разнообразным меню",
                            IsActive = true,
                            Name = "Yalla Cafe",
                            Phone = "+992901234567"
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.RestaurantAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RestaurantId");

                    b.ToTable("RestaurantAdmins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "yalla@qrmenu.com",
                            Name = "Yalla Manager",
                            PasswordHash = "$2a$11$Thh.HqMglp.WHyPmw353tucW4uCPg0yTWxkZdFqXjf.J/oY66niH2",
                            RestaurantId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RestaurantId", "Number")
                        .IsUnique();

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Capacity = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MenuId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Столик у окна",
                            Number = 1,
                            QrCode = "",
                            RestaurantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Type = 0
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastLoginAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Тестовый пользователь",
                            Phone = "+992901234567"
                        });
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Category", b =>
                {
                    b.HasOne("QrMenu.Core.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Menu", b =>
                {
                    b.HasOne("QrMenu.Core.Entities.Restaurant", "Restaurant")
                        .WithMany("Menus")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.MenuCategory", b =>
                {
                    b.HasOne("QrMenu.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QrMenu.Core.Entities.Menu", "Menu")
                        .WithMany("MenuCategories")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Order", b =>
                {
                    b.HasOne("QrMenu.Core.Entities.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QrMenu.Core.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("QrMenu.Core.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QrMenu.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Product", b =>
                {
                    b.HasOne("QrMenu.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QrMenu.Core.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.ProductAddon", b =>
                {
                    b.HasOne("QrMenu.Core.Entities.Product", "Product")
                        .WithMany("Addons")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.ProductSize", b =>
                {
                    b.HasOne("QrMenu.Core.Entities.Product", "Product")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.RestaurantAdmin", b =>
                {
                    b.HasOne("QrMenu.Core.Entities.Restaurant", "Restaurant")
                        .WithMany("RestaurantAdmins")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Table", b =>
                {
                    b.HasOne("QrMenu.Core.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QrMenu.Core.Entities.Restaurant", "Restaurant")
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Menu", b =>
                {
                    b.Navigation("MenuCategories");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Product", b =>
                {
                    b.Navigation("Addons");

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Restaurant", b =>
                {
                    b.Navigation("Menus");

                    b.Navigation("RestaurantAdmins");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.Table", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("QrMenu.Core.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
