// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QrMenu.Infrastructure.Data;

#nullable disable

namespace QrMenu.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223100000_SimplifyOrderStatuses")]
    partial class SimplifyOrderStatuses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This migration only updates data, no schema changes
            // The model is the same as the previous migration
#pragma warning restore 612, 618
        }
    }
}
